rootProject.name = "bricks"
include("game")
include("server")
include("client")
include("tournament")
include("tournament")
include("test")
include("events")
include("shared-web")
include("bots")
include("api")
include("auth")
include("lobbies")
